# Site settings
title: Iran University of Science and Technology
course_name: computer systems security
Overview: 6.858 Computer Security studies the design and implementation of secure computer systems. Lectures cover threat models, attacks that compromise security, and techniques for achieving security, based on recent research papers. Topics include operating system (OS) security, capabilities, information flow control, language security, network protocols, hardware security, and security in web applications. Assignments include labs that involve implementing and compromising a secure web server and web application, and a group final project.
course_semester: "Fall 2019"
description: |
    Instructor: DR. Zeinab Movahedi

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/CSE" # the subpath of your site, e.g. /blog/
url: "https://mahdi-javid.github.io/CSE" # the base hostname & protocol for your site
syllabus: https://mahdi-javid.github.io/CSE/syllabus/
githubdir: 

# Author/user information
Tel: +98(21)73225337
email: zmovahedi@iust.ac.ir
twitter_username:  
github_username:  
authorurl: "http://webpages.iust.ac.ir/zmovahedi/"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
