# Site settings
title: Iran University of Science and Technology
course_name: computer systems security
course_description: In this course, we aim to introduce students to Network Security & Computer Systems Security.
course_semester: "Fall 2019"
description: |
    Instructor: DR. Zeinab Movahedi

message: #Please register to our Google <a href="https://groups.google.com/forum/#!forum/gp-id">groups page</a> to get course notifications via email.
baseurl: "/computer-systems-security" # the subpath of your site, e.g. /blog/
url: "https://mahdi-javid.github.io/computer-systems-security" # the base hostname & protocol for your site
syllabus: https://mahdi-javid.github.io/computer-systems-security/syllabus/
githubdir: 

# Author/user information
email: zmovahedi@iust.ac.ir
twitter_username: broken_twitter 
github_username:  broken_github
authorurl: "http://webpages.iust.ac.ir/zmovahedi/"
address: |
    School of Computer Engineering
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false

sass:
    style: :compressed        

defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
      comments: false



plugins:
    - jekyll-jalali
